### ISSUE TITLE
Issue with App

### ISSUE THREAD

**Issue by ksgriff88** [DSchof1/CBB-Stats#2]
First I love what you have done here! Pretty incredible. I am very new to R but trying to run the code I am getting this error:

![Screenshot 2024-01-09 161530](https://github.com/DSchof1/CBB-Stats/assets/14319320/9cc65a5b-2fae-4c6d-b96d-06cc248e6f63)

Secondly would you be able to create a code that uses this as a base which would automatically show all the days (or upcoming X days) matchups and prediction?

Thank you!

**Comment by DSchof1** [comment]
That's an odd error, I don't think I've ever seen it.  Can you provide more context for when you saw this occur, ie if you had selected any inputs or clicked simulate, anything like that?  Does the app still run or will it not load due to this error?  

I'm currently working on making a schedule page, but it's going to take a while.  I'm just one person and don't always have a ton of time to devote to this project.

**Comment by ksgriff88** [comment]
I completely understand. If I can get ramped up in R I would definitely love to try to help!

As for the error I ran the App code, it runs through and tries to open the app and newly created webpage. I see it pop up and then it closes and shows the error. (Using Rstudio if that helps)

**Comment by DSchof1** [comment]
I've pushed a fix.  I was using a rather outdated version of R and RStudio that didn't raise the error, but as soon as I updated I started getting the same error as you.  Turns out it was a problem with the formatting in shinyalert, it should be fixed now.  Go ahead and pull the latest version.  

Feel free to reach out if you find further issues or want to contribute to the project.
